services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vyapari_db
      MYSQL_USER: vyapari_user
      MYSQL_PASSWORD: vyapari_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  vyapari-services:
    build:
      context: .
    container_name: vyapari-services
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vyapari_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: vyapari_user
      SPRING_DATASOURCE_PASSWORD: vyapari_pass
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql

volumes:
  mysql-data: