apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-listing-service-app
spec:
  selector:
    matchLabels:
      app: search-listing-service-app
  template:
    metadata:
      labels:
        app: search-listing-service-app
    spec:
      containers:
        - name: search-listing-service-app
          image: IMAGE_URL/search-listing-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9191

---

apiVersion: v1
kind: Service
metadata:
  name: search-listing-service-svc
spec:
  selector:
    app: search-listing-service-app
  ports:
    - port: 80
      targetPort: 9191